# PlantVillage 38-class label list — must match model training order exactly
CLASS_NAMES = [
    "Apple___Apple_scab",
    "Apple___Black_rot",
    "Apple___Cedar_apple_rust",
    "Apple___healthy",
    "Blueberry___healthy",
    "Cherry_(including_sour)___Powdery_mildew",
    "Cherry_(including_sour)___healthy",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)___Common_rust_",
    "Corn_(maize)___Northern_Leaf_Blight",
    "Corn_(maize)___healthy",
    "Grape___Black_rot",
    "Grape___Esca_(Black_Measles)",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
    "Grape___healthy",
    "Orange___Haunglongbing_(Citrus_greening)",
    "Peach___Bacterial_spot",
    "Peach___healthy",
    "Pepper,_bell___Bacterial_spot",
    "Pepper,_bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Raspberry___healthy",
    "Soybean___healthy",
    "Squash___Powdery_mildew",
    "Strawberry___Leaf_scorch",
    "Strawberry___healthy",
    "Tomato___Bacterial_spot",
    "Tomato___Early_blight",
    "Tomato___Late_blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_leaf_spot",
    "Tomato___Spider_mites Two-spotted_spider_mite",
    "Tomato___Target_Spot",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato___Tomato_mosaic_virus",
    "Tomato___healthy",
]

# Disease information: description, treatment tips, and healthy flag
DISEASE_INFO = {
    "Apple___Apple_scab": {
        "display": "Apple Scab",
        "isHealthy": False,
        "description": "A fungal disease caused by Venturia inaequalis. Causes olive-green to black lesions on leaves and fruits, leading to reduced yield and fruit quality.",
        "treatment": [
            "Apply fungicides (captan or myclobutanil) early in the season",
            "Remove and destroy fallen infected leaves",
            "Prune to improve air circulation",
            "Choose scab-resistant apple varieties for future plantings",
        ],
    },
    "Apple___Black_rot": {
        "display": "Apple Black Rot",
        "isHealthy": False,
        "description": "Caused by Botryosphaeria obtusa. Produces brown leaf spots with purple margins ('frog-eye'), and causes fruit rot and cankers on branches.",
        "treatment": [
            "Prune out dead or cankered branches at least 15 cm below affected tissue",
            "Remove mummified fruits from the tree",
            "Apply copper-based fungicide during dormant season",
            "Maintain tree vigor through balanced fertilization",
        ],
    },
    "Apple___Cedar_apple_rust": {
        "display": "Cedar Apple Rust",
        "isHealthy": False,
        "description": "Caused by Gymnosporangium juniperi-virginianae. Produces bright orange-yellow spots on leaves. Requires both cedar/juniper and apple to complete its life cycle.",
        "treatment": [
            "Remove nearby cedar or juniper trees where possible",
            "Apply myclobutanil or mancozeb fungicide from pink to petal fall stage",
            "Plant rust-resistant apple varieties",
            "Monitor and treat early at bud break",
        ],
    },
    "Apple___healthy": {
        "display": "Healthy Apple",
        "isHealthy": True,
        "description": "Your apple plant appears healthy with no visible signs of disease. Keep up the good care!",
        "treatment": [
            "Continue regular watering and balanced fertilization",
            "Monitor for early signs of pest or disease",
            "Prune annually to maintain airflow and structure",
        ],
    },
    "Blueberry___healthy": {
        "display": "Healthy Blueberry",
        "isHealthy": True,
        "description": "Your blueberry plant looks healthy. Maintain its care routine for continued vigour.",
        "treatment": [
            "Keep soil pH between 4.5 and 5.5",
            "Mulch around the base to retain moisture",
            "Monitor for aphids and mummyberry disease",
        ],
    },
    "Cherry_(including_sour)___Powdery_mildew": {
        "display": "Cherry Powdery Mildew",
        "isHealthy": False,
        "description": "Caused by Podosphaera clandestina. Produces white powdery fungal growth on young leaves and shoots, stunting growth.",
        "treatment": [
            "Apply sulphur-based or potassium bicarbonate fungicide",
            "Avoid overhead irrigation",
            "Prune for better air circulation",
            "Remove and dispose of heavily infected shoots",
        ],
    },
    "Cherry_(including_sour)___healthy": {
        "display": "Healthy Cherry",
        "isHealthy": True,
        "description": "Your cherry plant is in good health. Continue your care routine.",
        "treatment": [
            "Water deeply but infrequently",
            "Watch for cherry leaf spot and brown rot",
            "Apply dormant oil spray in late winter",
        ],
    },
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "display": "Corn Gray Leaf Spot",
        "isHealthy": False,
        "description": "Caused by Cercospora zeae-maydis. Produces rectangular tan/grey lesions that run parallel to leaf veins, reducing photosynthetic area.",
        "treatment": [
            "Plant resistant corn hybrids",
            "Rotate crops away from maize for at least one season",
            "Apply triazole or strobilurin fungicides at early disease onset",
            "Till crop residue to reduce inoculum",
        ],
    },
    "Corn_(maize)___Common_rust_": {
        "display": "Corn Common Rust",
        "isHealthy": False,
        "description": "Caused by Puccinia sorghi. Produces brick-red to brown pustules on both leaf surfaces, weakening the plant.",
        "treatment": [
            "Plant certified rust-resistant hybrid varieties",
            "Apply mancozeb or azoxystrobin fungicide at early infection",
            "Monitor fields during warm, humid weather",
            "Destroy crop debris post-harvest",
        ],
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "display": "Corn Northern Leaf Blight",
        "isHealthy": False,
        "description": "Caused by Exserohilum turcicum. Produces large, cigar-shaped grey-green lesions on leaves, leading to significant yield loss.",
        "treatment": [
            "Plant resistant hybrids with Ht-gene resistance",
            "Apply foliar fungicides (propiconazole) at early tassel stage",
            "Rotate crops and till residue",
            "Avoid dense planting to improve airflow",
        ],
    },
    "Corn_(maize)___healthy": {
        "display": "Healthy Corn",
        "isHealthy": True,
        "description": "Your corn plant is healthy and growing well. Continue monitoring for common pests.",
        "treatment": [
            "Ensure adequate nitrogen levels at key growth stages",
            "Scout for earworm and aphid pressure",
            "Maintain irrigation during tasseling and silking",
        ],
    },
    "Grape___Black_rot": {
        "display": "Grape Black Rot",
        "isHealthy": False,
        "description": "Caused by Guignardia bidwellii. Produces brown circular lesions on leaves and mummifies berries, causing significant crop loss.",
        "treatment": [
            "Apply mancozeb or myclobutanil at bud break and through bloom",
            "Remove and destroy mummified berries",
            "Prune for canopy openness",
            "Avoid wetting foliage during irrigation",
        ],
    },
    "Grape___Esca_(Black_Measles)": {
        "display": "Grape Esca (Black Measles)",
        "isHealthy": False,
        "description": "A complex wood disease caused by multiple fungi. Symptoms include tiger-striped leaves, berry spotting, and sudden vine collapse.",
        "treatment": [
            "No chemical cure available; prune out infected wood",
            "Protect pruning wounds with fungicide paste",
            "Remove and destroy severely infected vines",
            "Avoid water stress and excessive fertilization",
        ],
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "display": "Grape Leaf Blight",
        "isHealthy": False,
        "description": "Caused by Pseudocercospora vitis. Produces angular dark lesions on leaves, leading to defoliation and reduced fruit quality.",
        "treatment": [
            "Apply copper-based fungicide or mancozeb",
            "Remove infected leaves from the vineyard",
            "Ensure good air circulation through training and pruning",
            "Avoid overhead irrigation",
        ],
    },
    "Grape___healthy": {
        "display": "Healthy Grape",
        "isHealthy": True,
        "description": "Your grapevine looks healthy. Maintain proper canopy management for continued productivity.",
        "treatment": [
            "Train vines for good sun exposure and airflow",
            "Scout weekly for powdery mildew and downy mildew",
            "Apply pre-emptive fungicide schedule during humid seasons",
        ],
    },
    "Orange___Haunglongbing_(Citrus_greening)": {
        "display": "Citrus Greening (HLB)",
        "isHealthy": False,
        "description": "Caused by Candidatus Liberibacter asiaticus, spread by the Asian citrus psyllid. Causes yellowing, misshapen bitter fruit, and eventually kills the tree. No cure exists.",
        "treatment": [
            "Remove and destroy infected trees immediately to prevent spread",
            "Control Asian citrus psyllid vectors with imidacloprid",
            "Do not move plant material out of affected areas",
            "Consult local agricultural authorities for eradication programmes",
        ],
    },
    "Peach___Bacterial_spot": {
        "display": "Peach Bacterial Spot",
        "isHealthy": False,
        "description": "Caused by Xanthomonas arboricola. Produces water-soaked lesions on leaves and fruits that turn brown and crack.",
        "treatment": [
            "Apply oxytetracycline or copper bactericides at petal fall",
            "Avoid overhead irrigation",
            "Plant resistant varieties where available",
            "Prune to improve air circulation",
        ],
    },
    "Peach___healthy": {
        "display": "Healthy Peach",
        "isHealthy": True,
        "description": "Your peach tree looks healthy. Continue your seasonal care routine.",
        "treatment": [
            "Apply dormant oil spray before bud break",
            "Thin fruit early for larger, higher-quality peaches",
            "Monitor for peach leaf curl in spring",
        ],
    },
    "Pepper,_bell___Bacterial_spot": {
        "display": "Pepper Bacterial Spot",
        "isHealthy": False,
        "description": "Caused by Xanthomonas euvesicatoria. Results in small water-soaked lesions that become brown and necrotic on leaves and fruit.",
        "treatment": [
            "Apply copper-based bactericide early in the season",
            "Use certified disease-free seed",
            "Avoid working in the field when plants are wet",
            "Rotate with non-solanaceous crops for 2+ years",
        ],
    },
    "Pepper,_bell___healthy": {
        "display": "Healthy Bell Pepper",
        "isHealthy": True,
        "description": "Your pepper plant appears healthy. Keep up the watering and fertilization schedule.",
        "treatment": [
            "Maintain consistent soil moisture to prevent blossom-end rot",
            "Scout for aphids and thrips regularly",
            "Side-dress with calcium nitrate mid-season",
        ],
    },
    "Potato___Early_blight": {
        "display": "Potato Early Blight",
        "isHealthy": False,
        "description": "Caused by Alternaria solani. Produces concentric ring 'target' lesions on older leaves, leading to defoliation and reduced tuber quality.",
        "treatment": [
            "Apply chlorothalonil or mancozeb at first symptom",
            "Rotate crops for 2–3 years away from potatoes",
            "Plant certified disease-free seed potatoes",
            "Maintain adequate plant nutrition, especially potassium",
        ],
    },
    "Potato___Late_blight": {
        "display": "Potato Late Blight",
        "isHealthy": False,
        "description": "Caused by Phytophthora infestans. The pathogen responsible for the Irish Famine. Water-soaked lesions spread rapidly in cool, wet conditions and destroy entire crops.",
        "treatment": [
            "Apply metalaxyl or cymoxanil + mancozeb fungicide preventively",
            "Remove and bag infected foliage — do not compost",
            "Destroy infected tubers far from the field",
            "Avoid overhead irrigation and hill up soil around plants",
        ],
    },
    "Potato___healthy": {
        "display": "Healthy Potato",
        "isHealthy": True,
        "description": "Your potato plant is healthy. Continue routine monitoring during the growing season.",
        "treatment": [
            "Hill soil around plants when 30 cm tall",
            "Monitor weekly for late blight during wet weather",
            "Ensure adequate potassium for tuber development",
        ],
    },
    "Raspberry___healthy": {
        "display": "Healthy Raspberry",
        "isHealthy": True,
        "description": "Your raspberry plant looks healthy. Maintain pruning and support for best yield.",
        "treatment": [
            "Prune out old fruiting canes after harvest",
            "Train new canes to support wires",
            "Scout for raspberry cane borer and spider mites",
        ],
    },
    "Soybean___healthy": {
        "display": "Healthy Soybean",
        "isHealthy": True,
        "description": "Your soybean plant appears healthy. Monitor throughout the growing season.",
        "treatment": [
            "Ensure proper nodulation for nitrogen fixation",
            "Scout for soybean aphid and bean pod mottle virus",
            "Rotate with corn to break disease cycles",
        ],
    },
    "Squash___Powdery_mildew": {
        "display": "Squash Powdery Mildew",
        "isHealthy": False,
        "description": "Caused by Podosphaera xanthii. White powdery fungal patches appear on leaf surfaces, reducing photosynthesis and plant vigour.",
        "treatment": [
            "Apply potassium bicarbonate or neem oil at first sign",
            "Remove heavily infected leaves",
            "Improve air circulation by spacing plants adequately",
            "Avoid excess nitrogen fertilization",
        ],
    },
    "Strawberry___Leaf_scorch": {
        "display": "Strawberry Leaf Scorch",
        "isHealthy": False,
        "description": "Caused by Diplocarpon earlianum. Produces small purple spots that enlarge and coalesce, causing leaf edges to brown as if scorched.",
        "treatment": [
            "Remove and destroy infected leaves",
            "Apply captan or myclobutanil fungicide",
            "Renovate overcrowded beds to improve airflow",
            "Avoid overhead irrigation; use drip irrigation instead",
        ],
    },
    "Strawberry___healthy": {
        "display": "Healthy Strawberry",
        "isHealthy": True,
        "description": "Your strawberry plant is healthy. Continue good cultural practices for a productive harvest.",
        "treatment": [
            "Mulch with straw to keep fruit clean and retain moisture",
            "Remove runners that are not needed for propagation",
            "Scout for two-spotted spider mites in hot, dry weather",
        ],
    },
    "Tomato___Bacterial_spot": {
        "display": "Tomato Bacterial Spot",
        "isHealthy": False,
        "description": "Caused by Xanthomonas spp. Water-soaked spots become brown and necrotic on leaves and fruits, reducing marketability.",
        "treatment": [
            "Apply copper + mancozeb bactericide weekly",
            "Use certified disease-free transplants",
            "Avoid working among wet plants",
            "Rotate crops for 2 years",
        ],
    },
    "Tomato___Early_blight": {
        "display": "Tomato Early Blight",
        "isHealthy": False,
        "description": "Caused by Alternaria solani. Dark concentric-ring lesions appear on older leaves, causing premature defoliation and reduced fruit size.",
        "treatment": [
            "Apply chlorothalonil or azoxystrobin at 7–10 day intervals",
            "Mulch to prevent soil splash onto lower leaves",
            "Remove infected lower leaves",
            "Maintain balanced nutrition; avoid nitrogen excess",
        ],
    },
    "Tomato___Late_blight": {
        "display": "Tomato Late Blight",
        "isHealthy": False,
        "description": "Caused by Phytophthora infestans. Dark water-soaked lesions spread rapidly in cool, moist conditions. Fruits develop firm, brown rot.",
        "treatment": [
            "Remove and destroy affected plant parts immediately",
            "Apply copper-based fungicide or metalaxyl",
            "Improve air circulation around plants",
            "Water at the base, not on foliage",
        ],
    },
    "Tomato___Leaf_Mold": {
        "display": "Tomato Leaf Mold",
        "isHealthy": False,
        "description": "Caused by Passalora fulva. Olive-green to grey mould develops on the underside of leaves; upper surface shows pale yellow patches.",
        "treatment": [
            "Reduce humidity by improving greenhouse ventilation",
            "Apply mancozeb or copper fungicide",
            "Remove and destroy infected leaves",
            "Avoid wetting foliage during irrigation",
        ],
    },
    "Tomato___Septoria_leaf_spot": {
        "display": "Tomato Septoria Leaf Spot",
        "isHealthy": False,
        "description": "Caused by Septoria lycopersici. Small circular spots with dark borders and lighter centres appear on older leaves, leading to defoliation.",
        "treatment": [
            "Remove and destroy infected lower leaves",
            "Apply chlorothalonil or mancozeb fungicide",
            "Stake plants to improve air circulation",
            "Mulch to reduce soil-splash transmission",
        ],
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "display": "Tomato Spider Mites",
        "isHealthy": False,
        "description": "Caused by Tetranychus urticae. Mites feed on leaf undersides causing stippling, bronzing, and webbing. Populations explode in hot, dry conditions.",
        "treatment": [
            "Apply insecticidal soap or neem oil spray",
            "Release predatory mites (Phytoseiulus persimilis)",
            "Increase humidity and avoid water stress in plants",
            "Avoid broad-spectrum insecticides that kill natural enemies",
        ],
    },
    "Tomato___Target_Spot": {
        "display": "Tomato Target Spot",
        "isHealthy": False,
        "description": "Caused by Corynespora cassiicola. Produces concentric ring lesions on leaves, stems, and fruits. Favoured by high humidity and warm temperatures.",
        "treatment": [
            "Apply azoxystrobin or boscalid fungicide",
            "Remove and destroy infected plant material",
            "Improve air circulation through staking and pruning",
            "Rotate with non-solanaceous crops",
        ],
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "display": "Tomato Yellow Leaf Curl Virus",
        "isHealthy": False,
        "description": "Caused by TYLCV, transmitted by whiteflies. Leaves curl upward and turn yellow; growth is severely stunted and fruit set is poor.",
        "treatment": [
            "Control whitefly populations with imidacloprid or neem oil",
            "Use reflective mulches to deter whiteflies",
            "Plant TYLCV-resistant tomato varieties",
            "Remove and destroy infected plants promptly",
        ],
    },
    "Tomato___Tomato_mosaic_virus": {
        "display": "Tomato Mosaic Virus",
        "isHealthy": False,
        "description": "Caused by ToMV. Produces mosaic yellowing, leaf distortion, and mottling. Spread by contact, tools, and infected seeds.",
        "treatment": [
            "Use certified virus-free seed or resistant varieties",
            "Disinfect tools with 10% bleach solution",
            "Remove and destroy infected plants",
            "Wash hands thoroughly before handling plants",
        ],
    },
    "Tomato___healthy": {
        "display": "Healthy Tomato",
        "isHealthy": True,
        "description": "Your tomato plant is healthy and looking great! Keep up your care routine.",
        "treatment": [
            "Water consistently at the base to prevent blossom-end rot",
            "Support heavy fruit trusses with stakes or cages",
            "Scout weekly for early blight and late blight",
        ],
    },
}
